services:
  - type: web
    name: sync369-relay
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn symbolic_relay_fastapi:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000